service: cake-ordering-system
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  createOrder:
    handler: handler.createOrder
    events:
      - http:
          path: /order
          method: post
    environment:
      orderTableName: ordersTable

resources:
  Resources:
    orderEventsStrem:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: order-events
        ShardCount: 1
      orderTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: ordersTable
          AttributeDefinitions:
            - AttributeName: "orderId"
              AttributeType: "S"
          KeySchema:
            - AttributeName: "orderId"
              KeyType: "HASH"
          BillingMode: PAY_PER_REQUEST

