service: cake-ordering-system
plugins:
  - serverless-pseudo-parameters
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
      Resource:
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/ordersTable
    - Effect: Allow
      Action:
        - kineses:PutRecord
      Resource:
        - arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/order-events

functions:
  createOrder:
    handler: handler.createOrder
    events:
      - http:
          path: /order
          method: post
    environment:
      orderTableName: ordersTable
      orderStreamName: order-events

resources:
  Resources:
    orderEventsStrem:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: order-events
        ShardCount: 1
      orderTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: ordersTable
          AttributeDefinitions:
            - AttributeName: "orderId"
              AttributeType: "S"
          KeySchema:
            - AttributeName: "orderId"
              KeyType: "HASH"
          BillingMode: PAY_PER_REQUEST

